language: R
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      r: oldrel
      sudo: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
      r: release
    - os: linux
      dist: trusty
      r: devel
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
